### ISSUE TITLE
App not created as indicated

### ISSUE THREAD

**Issue by alexandrefierro** [telamonian/jupyter-osx-app#1]
Greetings:

(Mac OS 10.12.6)

Not really knowing what a "jupyter-repo-path" is supposed to be [I don't use GIT nor Mercurial], I simply moved the unzipped jupyter-app-master directory into:

/Users/alex.fierro/anaconda3/

and entered

/Users/alex.fierro/anaconda3/jupyter-app-master(525)>./install

I get this:

downloading vanilla google chrome...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 75.1M  100 75.1M    0     0  90.6M      0 --:--:-- --:--:-- --:--:-- 90.8M
done

installing vanilla google chrome...
done

cleaning up google chrome install files...
done

changing app icon from chrome to jupyter...
done

renaming chrome executable...
done

copying outer wrapper script over to app...
setting vars in outer wrapper script...
done

copying inner wrapper script over to app...
setting vars in inner wrapper script...
done

Modifying app's Info.plist to point to executable scripts...
done

Modifying app's Info.plist...
done

Adding extension manifests to "/Users/alex.fierro/Library/Application Support/Jupyter/External Extensions"...
done

but could not locate any such Jupyter app in the /Applications folder. This script instead creates an app called "google chrome" that just freezes upon launch. In terms of semantics, this isn't what I'd call a genuine "stand alone" app, because the 200+ MB Google Chrome Exec is needed. This is an inconvenience for users like myself who primarily use Firefox-Mozilla because it is far easier to customize this browser's interface either with CSS coding or third-party add-ons. Anyhow I went ahead and installed the latest version of Chrome to give it a try but seems like your installation script is failing somewhere?.

Cheers and thanks,

**Comment by telamonian** [comment]
Some of the components of my install script seem to have atrophied with time. I just finished pushing a bunch of fixes for it, so could you please pull the latest version of this repository and try it again? 

Here's what should happen once you execute `./install`

- An app named `Jupyter.app` will get added to your `/Applications` directory.
- When you double click on `Jupyter.app`, a terminal window and then a browser window will open. The terminal window will run the Jupyter server, while the browser window will show the Jupyter file browser.

The first time you run `Jupyter.app`, you may need to right click it and hit "Open" in order to get it to work. You'll probably see some popups asking for permission. Hit okay, and you shouldn't see them the next time it runs.

If the new install script still doesn't work for you, we can debug your problem like so:

- open a terminal window.
- type `/Applications/Jupyter.app/Contents/MacOS/Jupyter` and hit enter.
- tell me what happens/what text is produced.

**Comment by alexandrefierro** [comment]
Hi Max:

Works now without a hitch. Vielen Dank !

**Comment by telamonian** [comment]
Great! Glad it's working for you now.
