### ISSUE TITLE
Find a way to automatically terminate the jupyter notebook session when the linked browser is closed

### ISSUE THREAD

**Issue by willtownes** [telamonian/jupyter-osx-app#3]
This seems to have been solved by @almarklein (https://github.com/almarklein/jupyter_app) using webrunkit.

**Comment by telamonian** [comment]
The app in this repo already does this. Have you actually tried installing and running `telamonian/jupyter-app`? The browser will automatically close when the Jupyter server terminates, and the Jupyter server will terminate when the browser closes. This is accomplished via the bash `wait` command. You can see it in `resource/app_mid_wrap`

**Comment by willtownes** [comment]
Oh great, yeah I just tried it and it works fine. I created the issue only because I read it in your list of "future work" in the readme and assumed it wasn't available yet.

**Comment by telamonian** [comment]
Oh. Well then I should update that!

**Comment by telamonian** [comment]
The README now prominently mentions that server/browser shutdown is linked

**Comment by sperezconesa** [comment]
Hello,
I have installed this app and it works really nicely except for one thing. When I close the window with the red little bottom in the upper left corner the terminal stays open. If I close it from the docked icon I get the expected behavior. 

In addition when I launch it, a new icon is created in the bar and it looks as if I have to jupyterlabs open. Could this be changed? It is a rather picky detail hahaha.

Thank you for your help and this very nice app!
Best,
Sergio
